development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:010718c16981264dabd99720f3e5fc24@soapfish.redistogo.com:10571/
  channel_prefix: HANGOUT_production
